In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("data/02_processed/all_processed.csv")

In [4]:
data.head()

                                    canonical_smiles      pIC50
0  C=CC(=O)N1CC[C@H](Oc2nc(-c3n[nH]c(=O)[nH]3)cc3...  17.299989
1  C=CC(=O)N1CC[C@@H](C1)OC2=NC(=CC3=CC=CC=C32)C4...  12.000000
2  C=CC(=O)Nc1cc(Nc2nccc(-c3cn(C)c4ccccc34)n2)c(O...  11.698970
3  CN1C=C(C2=CC=CC=C21)C3=NC(=NC=C3)NC4=C(C=C(C(=...  11.698970
4    C1=CC=C2C=C3C(=CC2=C1)C(=NC=N3)NC4=CC(=CC=C4)Br  11.522879

In [5]:
data.sort_values("pIC50", ascending=False, inplace=True)

In [6]:
data.head()

                                    canonical_smiles      pIC50
0  C=CC(=O)N1CC[C@H](Oc2nc(-c3n[nH]c(=O)[nH]3)cc3...  17.299989
1  C=CC(=O)N1CC[C@@H](C1)OC2=NC(=CC3=CC=CC=C32)C4...  12.000000
3  CN1C=C(C2=CC=CC=C21)C3=NC(=NC=C3)NC4=C(C=C(C(=...  11.698970
2  C=CC(=O)Nc1cc(Nc2nccc(-c3cn(C)c4ccccc34)n2)c(O...  11.698970
5                  Brc1cccc(Nc2ncnc3cc4ccccc4cc23)c1  11.522879

In [ ]:
data["canonical_smiles"].head(1000).to_csv("mol2mol.smi", index=False)